/**
 * Functional core for the token editors (/playground, /theme-builder).
 * Pure serialization only — no DOM, no reactive state. Easy to unit-test.
 */

export type ShadowValue = {
	x: number;
	y: number;
	blur: number;
	spread: number;
	color: string; // hex, e.g. "#000000"
	alpha: number; // 0..1
};

export type TransitionValue = { duration: number; easing: string };

export type TokenValue =
	| { kind: 'length'; value: number; unit: 'px' | 'em' }
	| { kind: 'shadow'; value: ShadowValue }
	| { kind: 'font'; value: string }
	| { kind: 'transition'; value: TransitionValue }
	| { kind: 'color'; value: string };

export function hexToRgb(hex: string): { r: number; g: number; b: number } {
	const clean = hex.replace('#', '').trim();
	const full =
		clean.length === 3
			? clean
					.split('')
					.map((c) => c + c)
					.join('')
			: clean.padEnd(6, '0').slice(0, 6);
	return {
		r: parseInt(full.slice(0, 2), 16),
		g: parseInt(full.slice(2, 4), 16),
		b: parseInt(full.slice(4, 6), 16)
	};
}

export function shadowToCss(s: ShadowValue): string {
	const { r, g, b } = hexToRgb(s.color);
	const a = Math.round(s.alpha * 1000) / 1000;
	return `${s.x}px ${s.y}px ${s.blur}px ${s.spread}px rgb(${r} ${g} ${b} / ${a})`;
}

export function tokenToCss(v: TokenValue): string {
	switch (v.kind) {
		case 'length':
			return `${v.value}${v.unit}`;
		case 'shadow':
			return shadowToCss(v.value);
		case 'font':
			return v.value;
		case 'transition':
			return `${v.value.duration}ms ${v.value.easing}`;
		case 'color':
			return v.value;
	}
}

/** One CSS custom-property declaration line, tab-indented for a rule body. */
export function declLine(name: string, css: string): string {
	return `\t${name}: ${css};`;
}

export function generateModeCss(
	mode: 'soft' | 'hard',
	tokens: { name: string; value: TokenValue }[]
): string {
	const body = tokens.map((t) => declLine(t.name, tokenToCss(t.value))).join('\n');
	const label = mode === 'soft' ? 'SOFT' : 'HARD';
	return (
		`/* Character axis — ${label}. Generated by /playground. */\n` +
		`[data-mode='${mode}'] {\n${body}\n}\n`
	);
}

export function generateThemeCss(
	theme: string,
	roles: { name: string; hex: string }[]
): string {
	const body = roles.map((r) => declLine(r.name, r.hex)).join('\n');
	return (
		`/* Color axis — ${theme}. Generated by /theme-builder. */\n` +
		`[data-theme='${theme}'] {\n${body}\n}\n`
	);
}
